name: Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
      
    - name: Commit changes
      run: |
        #!/bin/bash
        
        set -e

        # Environment Variables
        REPO_URL="https://github.com/merson21/stupid-idea.git"
        GIT_USERNAME="merson21"
        GIT_EMAIL="mersontaguiam7@gmail.com"
        GHA_TOKEN="${{ secrets.GHA_TOKEN }}"
        GPG_PRIVATE_KEY="${{ secrets.GPG_PRIVATE_KEY }}"
        GPG_KEY_ID="${{ secrets.GPG_KEY_ID }}"
                
        # Get random commit message
        MESSAGES=("Update data" "Automated changes" "Daily commit" "Routine update" "Sync changes" "Minor adjustments")
        RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
        COMMIT_MESSAGE=${MESSAGES[$RANDOM_INDEX]}
        
        # Clone the repository
        git clone $REPO_URL
        cd stupid-idea
        
        # Make changes
        echo "$(date)" >> changes.txt
        
        # Configure Git
        git config --global user.name "$GIT_USERNAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgsign true
        
        # GPG setup
        export GNUPGHOME="${HOME}/.gnupg"
        mkdir -p "${GNUPGHOME}"
        chmod 700 "${GNUPGHOME}"

        # Kill any running gpg-agent
        if pgrep gpg-agent; then
          killall gpg-agent
        fi

        # Import the GPG private key
        echo "${GPG_PRIVATE_KEY}" | gpg --batch --import

        # Ensure GPG agent is running
        eval "$(gpg-agent --daemon)" > /dev/null 2>&1
        export GPG_TTY=$(tty)
        
        # Commit and push changes
        git add changes.txt
        git commit -S -m "$COMMIT_MESSAGE"
        git push https://${GHA_TOKEN}@github.com/merson21/stupid-idea.git main
        
        # Clean up
        cd ..
        rm -rf stupid-idea
