name: Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Get random commit message
      id: commit_message
      run: |
        echo "Current UTC time: $(date -u)"
        MESSAGES=("Update data" "Automated changes" "Daily commit" "Routine update" "Sync changes" "Minor adjustments")
        RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
        echo "COMMIT_MESSAGE=${MESSAGES[$RANDOM_INDEX]}" >> $GITHUB_ENV

    - name: Commit changes
      run: |
        git clone https://github.com/merson21/stupid-idea.git
        cd stupid-idea
        echo "$(date)" >> changes.txt
        git config --global user.name 'merson21'
        git config --global user.email 'mersontaguiam7@gmail.com'
        git add changes.txt
        git commit -m "$COMMIT_MESSAGE"
        git push https://${{ secrets.GHA_TOKEN }}@github.com/merson21/stupid-idea.git main
