name: Auto Commit
on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        trust_level: 5

    - name: List keys
      run: gpg -K

      
    - name: Sign commit and push changes
      run: |
        # Configure Git
        git config --global user.name "merson21"
        git config --global user.email "mersontaguiam7@gmail.com"
        echo foo > bar.txt
        git add .
        git commit -S -m "This commit is signed!"
        git push
