name: Auto Commit
on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto commit
      run: |
        #!/bin/bash 
        
        # Environment Variables
        echo "REPO_URL=https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
        echo "Print REPO_URL :: $REPO_URL"
        # REPO_URL="https://github.com/merson21/stupid-idea.git"
        GIT_USERNAME="merson21"
        GIT_EMAIL="mersontaguiam7@gmail.com"
                        
        # Get random commit message
        MESSAGES=("Update data" "Automated changes" "Daily commit" "Routine update" "Sync changes" "Minor adjustments")
        RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
        COMMIT_MESSAGE=${MESSAGES[$RANDOM_INDEX]}
        
        # Clone the repository
        git clone $REPO_URL
        chmod +x *
        cd stupid-idea
        
        # Make changes
        echo "$(date)" >> changes.txt
        
        # GPG setup
        export GNUPGHOME="${HOME}/.gnupg"
        mkdir -p "${GNUPGHOME}"
        chmod 700 "${GNUPGHOME}"
        
        # Save GPG private key to a temporary file
        echo "$GPG_PRIVATE_KEY" > /tmp/gpg_private_key.asc
        chmod 700 *
        
        
        # Import GPG key from the temporary file
        eval "$(gpg-agent --daemon)" > /dev/null 2>&1
        export GPG_TTY=$(tty)
        gpg --import /tmp/gpg_private_key.asc
                
        # Configure Git
        git config --global user.name "$GIT_USERNAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgsign true
                
        # Commit and push changes
        git add changes.txt
        git commit -S -m "$COMMIT_MESSAGE"
        git push https://${GHA_TOKEN}@github.com/merson21/stupid-idea.git main
        
        # Clean up
        # cd ..      
        # rm -rf stupid-idea
        
        # Remove the temporary file
        # rm /tmp/gpg_private_key.asc    
        
      env:
        GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

