name: Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Import GPG key
      id: import_gpg
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        mkdir -m 700 ~/.gnupg
        # echo "disable-scdaemon" > ~/.gnupg/gpg.conf
        # cat ~/.gnupg/gpg.conf
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import-ownertrust

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
      
    - name: Commit changes
      run: |        
        # Environment Variables
        REPO_URL="https://github.com/merson21/stupid-idea.git"
        GIT_USERNAME="merson21"
        GIT_EMAIL="mersontaguiam7@gmail.com"
        GPG_KEY_ID="${{ secrets.GPG_KEY_ID }}"
        GHA_TOKEN="${{ secrets.GHA_TOKEN }}"         
        # echo "GPG_PRIVATE_KEY=${{ secrets.GPG_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "GPG_KEY_ID=${{ secrets.GPG_KEY_ID }}" >> $GITHUB_ENV
        echo "GHA_TOKEN=${{ secrets.GHA_TOKEN }}" >> $GITHUB_ENV
        
        # Set up GPG
        # mkdir -m 700 ~/.gnupg
        # cat <<EOF >~/.gnupg/gpg.conf
        # disable-scdaemon
        # EOF
        # echo "$GPG_PRIVATE_KEY" | gpg --import
        # echo "$GPG_PRIVATE_KEY" | gpg --import-ownertrust

        
        # Get random commit message
        MESSAGES=("Update data" "Automated changes" "Daily commit" "Routine update" "Sync changes" "Minor adjustments")
        RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
        COMMIT_MESSAGE=${MESSAGES[$RANDOM_INDEX]}
        
        # Clone the repository
        git clone $REPO_URL
        cd stupid-idea
        
        # Make changes
        echo "$(date)" >> changes.txt
        
        # Configure Git
        git config --global user.name "$GIT_USERNAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global user.signingkey "$GPG_KEY_ID"
        git config --global commit.gpgSign true
        
        # Commit and push changes
        git add changes.txt
        git commit -m "$COMMIT_MESSAGE"
        git push https://${GHA_TOKEN}@github.com/merson21/stupid-idea.git main
        
        # Clean up
        cd ..
        rm -rf stupid-idea
